### PR TITLE
Add services support list

### PR DESCRIPTION
**Pull request by DanielOaks**
This just adds the services support list as discussed in #49. I think these are the main services packages around -- are there any others we should be listing as well?

I don't have it showing a page in the proper 'Software' section, as services packages don't make use of the sort of extensions IRCv3 brings out generally. If this changes or there is more to add along these lines, we can do so later.

### CODE REVIEW

**Comment by Mikaela** [comment]
I think you forgot [ChatServices] (https://bitbucket.org/chatlounge/chatservices). 

Are not-SASL or IRCv3 compatible clients counted? There is e.g.https://github.com/dkorunic/hybserv2 which doesn't seem very alive.

**Comment by attilamolnar** [comment]
I think atheme forks should be listed together because there is little difference between them considering the overall codebase and no difference in sasl afaik. If one of them differs it should be listed seperately of course.

**Comment by attilamolnar** [comment]
> There is e.g.https://github.com/dkorunic/hybserv2 which doesn't seem very alive.

From their README:

> Hybserv2 is incompatible with IRCD Hybrid 8.x as they have decided to be TS3 incompatible. There is some grunt work needed to make it fully TS6 and I personally don't have any more time and interest to code or IRC and related to IRC. For me, IRC has long died, [...]

So no, it should not be listed as it is incompatible with the current version of the server it targets and its author no longer supports it.

**Comment by DanielOaks** [comment]
Alrighty, we now group Atheme forks together in the table. Should be fine to merge in that case?

**Comment by attilamolnar** [comment]
Please squash the commits (rebase if necessary)

**Comment by Mikaela** [comment]
:+1: if this PR is currently gathering :+1:s or is there some reason for not being merged already?

**Comment by DanielOaks** [comment]
I'll assume this is good to merge, as everything requested has been done.

**Comment by timofonic** [comment]
Why is this still open?

**Comment by DanielOaks** [comment]
This isn't, this was merged at the end of last year.

Services aren't listed on the ordinary software support lists, ie [these](http://ircv3.net/software/servers.html), as our specs apply to the Client protocol and don't really affect them very much. This info is used and linked on things like the [SASL](http://ircv3.net/docs/sasl-mechs.html) pages though!

**Pull request merged**
