### PR TITLE
Added BonoboNET

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by SadieCat** [comment]
Do you have any servers which are accessible without using Tor/I2P/etc? I'm not sure we have any rules about this but it doesn't seem useful to include servers that most people can't access.

**Comment by deavmi** [comment]
We have several IPv4/IPv6 servers accessible through the clearnet:

1. `41.157.98.109`/`2a04:5b81:2011::2`
2. `160.20.145.209`/`2a01:367:c1f2::254`
3. `2a04:5b81:2010::92`

**Comment by deavmi** [comment]
Would you like me to add one of the above to the list?

**Comment by deavmi** [comment]
@SadieCat ?

**Comment by deavmi** [comment]
Many thanks good sirs

**Pull request merged**
