### PR TITLE
Spec cleanup LOOKIE EXAMPLE

### PR DESCRIPTION
**Pull request by DanielOaks**
Yeah this is the spec cleanups in https://github.com/ircv3/ircv3-specifications/pull/441 but in here so we can have a look at it when Netlify builds it. **Don't merge this PR,** it will do weird stuff because of where I've applied the `specs` submodule changes from.

### CODE REVIEW

**Comment by jwheare** [comment]
Need to update URLs/fullnames in _data/specs.yml too.

**Comment by jwheare** [comment]
And _data/irc_versions.yml

**Comment by DanielOaks** [comment]
Sounds good, will do on the real PR (note to self, consider whether to change the `starttls` name in those files to `tls` considering that's what the cap and spec is called. I think I used `starttls` here to disambiguate between deprecated starttls and general like, TLS, the protocol though, so may just leave it).

**Comment by jwheare** [comment]
LGTM

**Comment by DanielOaks** [comment]
I can close this now, this is merged proper into the site

**Pull request closed without merging**
