### PR TITLE
Ratify labeled-response

### PR DESCRIPTION
**Pull request by jwheare**

### CODE REVIEW

**Comment by SadieCat** [comment]
InspIRCd has labeled-response support in v3 git (due to be v3.5.0 on Friday).

**Comment by kylef** [comment]
Palaver iOS has labeled-response support in master scheduled for next release of Palaver.

**Comment by slingamn** [comment]
This is in oragono's master branch. It's up on testnet.oragono.io currently, and should be up on darwin in a few days, but won't be in a stable release until late February at the earliest.

**Comment by jwheare** [comment]
The IRCCloud web, mobile clients as well as the server and bouncer (both sides) now support the unprefixed cap.

**Comment by jwheare** [comment]
Blog post preview is here: https://deploy-preview-294--ircv3.netlify.com/2020/01/30/replies-responses

**Comment by DanielOaks** [comment]
Nice. Short, sweet, simple

**Pull request merged**
