### PR TITLE
software: Separate and highlight the required cap columns

### LINKED ISSUE #18: Software: could base requirements be bolded (e.g. cap and all yes/no below it)
I think some kind of formatting would make it more clear what clients are required to have in order to be IRCv3.1 compatible.

### PR DESCRIPTION
**Pull request by dequis**
Preview: http://dump.dequis.org/LKeRZ.html

Current: http://ircv3.net/software/clients.html

Closes #18 

>I think some kind of formatting would make it more clear what clients are required to have in order to be IRCv3.1 compatible.
>
>Or group these columns in the left and separate from the rest by more think vertical line

I also made missing caps that are optional a lighter shade of red, since it's not wrong to not implement those. The current one gives off the appearance that everyone is doing everything wrong (the table is mostly red)

### CODE REVIEW

**Comment by jwheare** [comment]
+1 do it.

**Comment by jwheare** [comment]
Then merge #21 and close #17 too.

**Comment by jwheare** [comment]
There is consensus on IRC from anyone who has expressed an opinion and been active recently: @jwheare @dequis @Mikaela

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
