### PR TITLE
clients: Add AdiIRC.

### PR DESCRIPTION
**Pull request by Aerdan**

### CODE REVIEW

**Comment by Mikaela** [comment]
:-1: as AdiIRC isn't IRCv3.1 base compatible by missing SASL. I think it's better to leave not-compliant software out until https://github.com/ircv3/ircv3.github.io/issues/17#issuecomment-123927921 is implemented.

**Comment by DanielOaks** [comment]
Given that this doesn't support 3.1 core, I'll leave this out 'til we've
got the way to show non-compliant software merged.

**Comment by kaniini** [comment]
Isn't the whole point to show compliant software in order to encourage developers to participate in the compliance scheme?

**Comment by DanielOaks** [comment]
I think listing the software, but prominently negatively marking them would work better. Being able to display the status of IRCv3 implementation, even on software which isn't fully compliant, is useful because it lets people see the support for our specifications, and lets interested users see the software support across the board.

Clearly marking them negatively should dissuade people visiting the page from using them based on the link there. The main thing is to make sure we're not advertising the software that's not compliant, so I'm keeping that in mind while going through different options.

**Comment by jwheare** [comment]
+1 for including as much software as possible on these lists. Compatibility is indicated in the matrix, inclusion by no means indicates endorsement. I personally would love to be able to see how far ahead different clients are with support, even if they only support one CAP. And yes, mIRC should be on this list, and not buried away in a forum where it can't be easily compared with other clients http://forums.mirc.com/ubbthreads.php/topics/244662/IRCv3

**Comment by jwheare** [comment]
Oh my bad, mIRC is already on the list. Good!

**Comment by jwheare** [comment]
There is consensus on IRC from anyone who has expressed an opinion and been active recently: @jwheare @dequis @Mikaela

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
