### PR TITLE
Update spec submodule, add account-registration and extended-monitor

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by progval** [comment]
oops, forgot some draft tags

**Comment by jwheare** [comment]
Alright, this should be good to go, can spec authors @progval @emersion please check that these pages are rendering correctly (links, examples, headings, formatting etc) and that there are no glaring errors:

https://deploy-preview-421--ircv3.netlify.app/specs/extensions/extended-monitor
https://deploy-preview-421--ircv3.netlify.app/specs/extensions/account-registration

**Comment by progval** [comment]
yup

**Comment by emersion** [comment]
Acked-by me

**Pull request merged**
