### PR TITLE
software: Add OS icons for mobile clients

### PR DESCRIPTION
**Pull request by DanielOaks**
Adds OS icons for mobile clients, as #20 

Looks like this:
Mobile Clients page

### CODE REVIEW

**Comment by jwheare** [comment]
Looks great

**Comment by Mikaela** [comment]
:+1: something like that would also be nice for desktop clients, but mobile probably does need it more.

**Comment by Mikaela** [comment]
Or wait, how do you separate OS X from iOS and Windows Mobile from Windows (when/if my previous comment happens)?

Just taking a look at mobile clients versus desktop clients or is there a separate logo availble for it?

**Comment by DanielOaks** [comment]
No separate logo available, code-wise it's named differently so it'll have a different hover-over name, but I think being in the Desktop/Mobile categories will separate them enough. We can look at desktop clients after mobile ones get it, though.

**Comment by dequis** [comment]
:+1:, i think the title="..." attribute (mouseover/tooltip text) is enough

**Comment by attilamolnar** [comment]
LGTM

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
