### PR TITLE
Add jess to the Technical Board

### PR DESCRIPTION
**Pull request by jwheare**
@jesopo please confirm you are on board with this.

### CODE REVIEW

**Comment by jesopo** [comment]
minorly surprised, majorly honoured, happy to immediately say yes to representing bitbot, but we're going to pull up a vote in a meeting for the libera.chat bit just to be sure we're happy with my silliness representing the org.

**Comment by prawnsalad** [comment]
I haven't seen this addition mentioned anywhere, but I don't think someone that actively pushes lies and false information  about other members and projects in the workgroup should be welcomed to the technical board. I'm sure everyone knows about the freenode/libera.chat drama, but despite trying to to stay entirely out of it personally, @jesopo was an active (and continues to create accounts on forums to mis-represent information) person in spreading false information about IRC projects and myself despite being corrected several times - and despite being unrelated to freenode.

It sounds like this has already been decided somewhere, unsure where, but this is a -1 from myself on these grounds. Completely open to revisiting in future though if this is an option.

**Comment by jwheare** [comment]
This has been discussed favourably a number of times in IRC, but no decision has been made. That's why this is a PR and not a direct commit. See previous PRs where people have been suggested for board inclusion.

The proposal is based on recognising contributions to the IRCv3 project and to the IRC ecosystem in general, from both community and technical points of view. The allegations you've raised here will need to be discussed further to determine if they have any merit, but I don't think it would be productive to have a heated personal argument in this comment thread. I'm happy to discuss in private with you both and report back here with any resolution.

**Comment by prawnsalad** [comment]
@jwheare  Sure thing - no intention to debate this here either. I'll PM you info then.

**Comment by ddevault** [comment]
Wow, I find it astonishing to see grossly unsubstantiated libel of that degree coming out on a technical advisory board, @prawnsalad. You had better back that up with some evidence or you are *way* out of line.

**Comment by SadieCat** [comment]
@ddevault This matter is being resolved privately.

**Comment by ddevault** [comment]
Well, the accusations were made publicly, so you're beyond that now.

**Comment by prawnsalad** [comment]
@ddevault You've probably misunderstood. My comment had nothing to do with Libera Chat or being a representative of it. As mentioned above, this thread is not to be turned into a heated argument which is why I left the drama side of pasting logs etc out of it and simply mentioned the reasoning. Please do the same and keep this thread solely for its topic.

**Comment by ddevault** [comment]
>I don't think someone that actively pushes lies and false information about other members and projects in the workgroup should be welcomed to the technical board.

You threw these stones, @prawnsalad, don't appeal to a higher cause of avoiding drama.

**Comment by jwheare** [comment]
None of these comments are contributing anything of value. The matter is being handled and the resolution will be posted publicly.

**Comment by jwheare** [comment]
None of these comments are contributing anything of value. The matter is being handled and the resolution will be posted publicly.

**Comment by DanielOaks** [comment]
Jess, for what I've seen, doesn't push lies and false information @prawnsalad. I know this is being dealt with privately but, no, I haven't seen any instances of her doing **anything** of the sort. Making those sort of accusations honestly calls your conduct here (in this issue) into question in my mind. If you want to try to convince me otherwise, my PMs are open.

Jess would make a great addition to the board, her work on bitbot, spec stuff, and other associated work around the IRC sphere have been and continue to be great. She'd make a perfect addition to the board, and I do not want to see this 'revisited later'.

**Comment by jwheare** [comment]
Having spoken to both @jesopo and @prawnsalad and looked at various logs and posts, I have found no evidence of the alleged lies. There is nothing here that should affect the make up of the IRCv3 technical board.

There has been a huge amount of (valid) emotive grievance airing and lots of insinuations flying around over the freenode/libera split. Various things were posted elsewhere without clarification that have now been made more clear. I can understand the stress and upset everyone is feeling, but this is now a private matter and should be resolved as such. Please maintain respect for the people involved.

I want to reiterate that membership of the board is largely an indicator of interest and investment in the IRCv3 project. We do not have a voting system, we strive for as broad a consensus as possible, sometimes with compromise. The board is a selection of people with a level of two-way trust in and from the project. They do not always agree, and decisions will not always go their way (and that includes the chair) but they are all on board with the goals of the project, and have demonstrated trusted contributions over time.

I also want to strongly stress that contributions and input are by no means limited to board members. We try to consider the IRC ecosystem as a whole. We seek and value a wide variety of view points. Many specs originate and are worked on by non-board members.

That said, the board system may not be the best model for what we do. I'm open to suggestions for how to improve or replace it, please open a new issue if you've got a good one.

In the mean time, it looks like there is overwhelming support for @jesopo's appointment, but I will leave this PR open for a while longer to allow for any further input.

**Comment by jesopo** [comment]
> we're going to pull up a vote in a meeting for the libera.chat bit just to be sure we're happy with my silliness representing the org.

answer was yes

**Pull request merged**
