### PR TITLE
add Libera.Chat to _data/su_networks.yml

### PR DESCRIPTION
**Pull request by jesopo**

### CODE REVIEW

**Comment by jesopo** [comment]
how come that test failed?

**Comment by ProgVal** [comment]
It's also failing on the main branch

**Comment by jesopo** [comment]
oh, that sounds like not my problem, fantastic!

**Comment by DanielOaks** [comment]
Yeah for some reason my yaml check stuff is messing up when working out the type of a new variable I added. gotta look into it at some point, but nothing to do with this PR. Thanks!

**Pull request merged**
