### PR TITLE
Update participants and TC list

### PR DESCRIPTION
**Pull request by progval**
Roughly based on activity on #ircv3 and github.

Everyone added, please reply to confirm you want to be on the list:

- [x] @delthas 
- [x] @emersion (both as yourself and Sourcehut)
- [ ] ~~@causal-agent~~
- [x] @ValwareIRC 

I removed WillowChat because they seem inactive since 2018

### CODE REVIEW

**Comment by emersion** [comment]
Sounds good, thanks!

**Comment by ValwareIRC** [comment]
cool with me =]

**Comment by delthas** [comment]
Yes 

thanks

**Comment by ValwareIRC** [comment]
bumpity bump

**Pull request merged**
