### PR TITLE
Update WeeChat client support with version 4.0.0

### PR DESCRIPTION
**Pull request by flashcode**
Now supported in v4.0.0:
- batch
- echo-message
- multiline
- utf8only

Already supported: bot-mode.

### CODE REVIEW

**Comment by progval** [comment]
what does weechat do with the bot mode?

**Comment by flashcode** [comment]
@progval: nothing specific, but the message 335 is correctly handled and displayed, and the WHO bot flag should be just displayed as-is.

**Comment by progval** [comment]
I see, thx

**Comment by jwheare** [comment]
Thanks, can you also remove the version number from anything less than 3.6 (more than a year old)

**Comment by flashcode** [comment]
@jwheare: done.

**Pull request merged**
