### PR TITLE
Update link to SCRAM-SHA-256's RFC.

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Mikaela** [comment]
It looks wrong when compared to PLAIN/EXTERNAL, could you copy them?

**Comment by ProgVal** [comment]
Done.

**Comment by Mikaela** [comment]
Squash would peobably be the next thing?

**Comment by ProgVal** [comment]
Why?

**Comment by attilamolnar** [comment]
Please squash this

**Comment by Mikaela** [comment]
Because there are three commits and I see no reason why this couldn't be single commit.

**Comment by ProgVal** [comment]
Done.

**Comment by DanielOaks** [comment]
Thanks!

**Pull request merged**
